// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRBe35IcbCU5HmQG0_T3YSRiraVKK2tQA',
    appId: '1:572757404259:web:3fdad6d62e11fb6ca92656',
    messagingSenderId: '572757404259',
    projectId: 'lumina-6ff88',
    authDomain: 'lumina-6ff88.firebaseapp.com',
    storageBucket: 'lumina-6ff88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh8PZ4Zuuc2a0_w6CuHr_cJnYJcHeM8-U',
    appId: '1:572757404259:android:3a001528aa44470ea92656',
    messagingSenderId: '572757404259',
    projectId: 'lumina-6ff88',
    storageBucket: 'lumina-6ff88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXNaNKCPz1f4OOuf1LIvTaGmRN83Qyhks',
    appId: '1:572757404259:ios:924edf86e40b59f0a92656',
    messagingSenderId: '572757404259',
    projectId: 'lumina-6ff88',
    storageBucket: 'lumina-6ff88.firebasestorage.app',
    iosBundleId: 'com.example.lumina',
  );
}
